version: "3.9"

services:
  nginx:
    image: 2daye/nginx
    restart: always
    ports:
      - "8080:80"
    working_dir: /var/www
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.docker/config/nginx/conf.d:/etc/nginx/conf.d
      - ./.docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/config/nginx/ssl:/etc/nginx/ssl
      - ./code:/var/www
  php:
    image: 2daye/php:8.1.3-fpm
    restart: always
    working_dir: /var/www
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.docker/config/php/php.ini-production:/usr/local/etc/php/php.ini
      - ./.docker/config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./code:/var/www
  mysql:
    image: mysql:8.0.28
    restart: always
    ports:
      - "33062:3306"
    environment:
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: 123456
      character-set-server: utf8mb4
      collation-server: utf8mb4_unicode_ci
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.docker/data/mysql:/var/lib/mysql
  redis:
    image: 2daye/redis
    restart: always
    ports:
      - "63792:6379"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./.docker/config/redis/master.conf:/usr/local/etc/redis/redis.conf
      - ./.docker/data/redis:/data
  crontab:
    image: 2daye/crontab
    restart: always
    working_dir: /var/www
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./code:/var/www
      - ./.docker/config/crontab/default:/etc/cron.d/crontab/default
